baseURL = 'https://highSpeedcoolGuy.github.io/'
languageCode = 'en-us'
title = 'Jose Abuan | CS & Robotics'
theme = 'PaperMod'

[params]
    defaultTheme = "dark" # Perfect for the CS aesthetic
    showCodeCopyButtons = true

[[menu.main]]
    name = "Work Blog"
    url = "/posts"
    weight = 10

[[menu.main]]
    name = "14er Logs"
    url = "/hikes"
    weight = 20