baseURL = 'https://highSpeedcoolGuy.github.io/'
languageCode = 'en-us'
title = 'Jose Abuan | CS & Robotics'
theme = 'PaperMod'

[params]
    defaultTheme = "dark" # Perfect for the CS aesthetic
    showCodeCopyButtons = true
    mainSections = ["posts", "hikes"]
[params.homeInfoParams]
    Title = "Jose Abuan"
    Content = """
Welcome to my personal site! I am a **Computer Science** student at the **Colorado School of Mines**. 
When I'm not in the lab, you can find me hiking 14ers. 
"""

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/highSpeedcoolGuy"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jose-abuan" 
[[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com/@mynamehosehimenez"    
[[params.socialIcons]]
    name = "discord"
    url = "https://discordapp.com/users/jose_63032"    

[[params.socialIcons]]
    name = "email"
    email = "abuanjosel@gmail.com"   


[[menu.main]]
    name = "Work Blog"
    url = "/posts"
    weight = 10

[[menu.main]]
    name = "14er Logs"
    url = "/hikes"
    weight = 20